% Digital Current Feedback GUI for MATLAB 2010a <-> XMOS

function DCF
dll_path = 'C:\Thesycon\TUSBAudio_v1.22.0\EvaluationKit\DriverInstaller\release\';
h_path = 'C:\Thesycon\TUSBAudio_v1.22.0\EvaluationKit\DriverInstaller\release\DCF\';
%[NOTFOUND, WARNINGS] = loadlibrary([dll_path 'tusbaudioapi.dll'],[h_path 'tusbaudioapi.h'] );
%libfunctions('tusbaudioapi')

main_windows_pos=[100 100 800 600];
Z=zeros(128,1);
f=logspace(1,log10(1500),128);

s=tf([1 0],1);

fh = figure('Position',main_windows_pos,...
    'MenuBar','none',...
    'NumberTitle','off',...
    'Name','Digital Current Feedback');

s_BPfc = uicontrol(fh,'Style','slider',...
    'Max',120,'Min',10,'Value',50,...
    'SliderStep',[0.01 0.1],...
    'Position',[25 500 250 20],...
    'Callback',@slider_BPfc_callback);

s_BPQ = uicontrol(fh,'Style','slider',...
    'Max',10,'Min',0.1,'Value',1,...
    'SliderStep',[0.01 0.1],...
    'Position',[25 400 250 20],...
    'Callback',@slider_BPQ_callback);

s_BPG = uicontrol(fh,'Style','slider',...
    'Max',10,'Min',-10,'Value',0,...
    'SliderStep',[0.01 0.1],...
    'Position',[25 300 250 20],...
    'Callback',@slider_BPG_callback);
 
 s_Re = uicontrol(fh,'Style','slider',...
     'Max',10,'Min',-10,'Value',0,...
     'SliderStep',[0.01 0.1],...
     'Position',[25 200 250 20],...
     'Callback',@slider_Re_callback);
 
 
 et_BPfc = uicontrol(fh,'Style','edit',...
     'String',(['Fc=' num2str(get(s_BPfc,'Value')) ' Hz']),...
     'HorizontalAlignment','left',...
     'Position',[150 525 75 20],...
     'Callback',@edittext_BPfc_callback);

  et_BPQ = uicontrol(fh,'Style','edit',...
     'String',(['Q=' num2str(get(s_BPQ,'Value'))]),...
     'HorizontalAlignment','left',...
     'Position',[150 425 75 20],...
     'Callback',@edittext_BPQ_callback);
 
 et_BPG = uicontrol(fh,'Style','edit',...
     'String',(['R=' num2str(get(s_BPG,'Value')) ' Ohm']),...
     'HorizontalAlignment','left',...
     'Position',[150 325 75 20],...
     'Callback',@edittext_BPG_callback);
 
 et_Re = uicontrol(fh,'Style','edit',...
     'String',(['Re=' num2str(get(s_Re,'Value')) ' Ohm']),...
     'HorizontalAlignment','left',...
     'Position',[150 225 75 20],...
     'Callback',@edittext_Re_callback);

  t_L = uicontrol(fh,'Style','text',...
     'String','L(s)=1',...
     'HorizontalAlignment','left',...
     'Position',[100 125 125 40],...
     'Callback',@edittext_orm_callback);
 
 Fmax=1500;
 
 axes_Z=axes('Units','pixels','position',[350 100 400 400]);
 plot_Z=plot(f,real(Z),f,imag(Z),f,abs(Z),'linewidth',2);
 xlabel('Frekvens [Hz]');
 ylabel('Impedans [Ohm]');
 xlim([get(s_BPfc,'Min') Fmax]);
 ylim([-15 15]);
 grid on;
 set(axes_Z,'XScale','log');
 XTick=get(axes_Z,'XTick');set(axes_Z,'XTickLabel',num2str(XTick'));
 legend('Resistans','Reaktans','Impedans')
 title('Virtuell utimpedans')
 
function slider_BPfc_callback(hObject,eventdata)
set(et_BPfc,'String',['Fc=' num2str(round(10*get(s_BPfc,'Value'))*0.1) ' Hz']);
end

function slider_BPQ_callback(hObject,eventdata)
set(et_BPQ,'String',['Q=' num2str(round(100*get(s_BPQ,'Value'))*0.01)]);
end


function slider_BPG_callback(hObject,eventdata)
set(et_BPG,'String',['R=' num2str(round(10*get(s_BPG,'Value'))*0.1) ' Ohm']);
end

function slider_Re_callback(hObject,eventdata)
Re=get(s_Re,'Value');
set(et_Re,'String',['Re=' num2str(round(10*Re)*0.1) ' Ohm']);
updateL;
end

function updateL()
Re=get(s_Re,'Value');   
L=s/(1+s+s*s)+Re;
[mag,phase] = bode(L,f/2/pi);
%TO BE DONE set(plot_Z,'XData',[mag(:),mag(:),mag(:)]) cell!
end
end
